"""create inventory items table

Revision ID: 917410e16531
Revises: 9d2753d2e786
Create Date: 2026-09-25 10:27:26.935432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917410e16531'
down_revision: Union[str, Sequence[str], None] = '9d2753d2e786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_inventory_items_price_nonnegative'),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_items_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_inventory_items_user_id_name'),
    sa.UniqueConstraint('user_id', 'sku', name='uq_inventory_items_user_id_sku')
    )
    op.create_index(op.f('ix_inventory_items_user_id'), 'inventory_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_user_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
